In [33]:
import ray
import time
import numpy as np

In [34]:
# ray.init()

In [35]:
matrix_A = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix_B = np.array([[1,2,3], [4,5,6], [7,8,9]])
# matrix_C = np.zeros((3,3))
print(matrix_A)
print(matrix_B)
# print(matrix_C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
@ray.remote
def my_function(data):
    matrix_A, matrix_B, i = data
    matrix_C_element = 0
    x = i % 3
    y = i // 3
    matrix_C_element = matrix_A[x][y] + matrix_B[x][y]
    # time.sleep(2)
    # print(matrix_A)
    # print(matrix_B)
    # print(matrix_C)
    return(matrix_C_element)  

In [37]:
total_numbers = 9
numbers = []
for i in range(total_numbers):
    numbers.append(i)

result_ids = []
for i in numbers:
    data = (matrix_A, matrix_B, i)
    result_ids.append(my_function.remote(data))

results = []
for i in numbers:
    results.append(ray.get(result_ids[i]))

matrix_C = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        matrix_C[i][j] = results[j*3 + i]

print(matrix_C)


[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [38]:
#Assigment change the code from adding both matrices to multiplying both

import numpy as np
import ray

@ray.remote
def my_function(data):
    matrix_A, matrix_B, i = data
    x = i % 3
    y = i // 3
    matrix_C_element = 0
    for k in range(3):
        matrix_C_element += matrix_A[x][k] * matrix_B[k][y]
    return matrix_C_element

# Define matrices A and B
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the total number of elements in the matrices
total_numbers = 9
numbers = list(range(total_numbers))

# Execute the matrix multiplication 
result_ids = []
for i in numbers:
    data = (matrix_A, matrix_B, i)
    result_ids.append(my_function.remote(data))

# Gather results
results = ray.get(result_ids)

# Create matrix C for storing the result
matrix_C = np.zeros((3, 3))

# Fill matrix C with values
for i in range(3):
    for j in range(3):
        matrix_C[i][j] = results[j * 3 + i]

print(matrix_C)



[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [45]:
#Assigment change the code from adding both matrices to multiplying both

import numpy as np
import ray
dim = 100

@ray.remote
def my_function(data):
    matrix_A, matrix_B, i = data
    x = i % dim
    y = i // dim
    matrix_C_element = 0
    for k in range(dim):
        matrix_C_element += matrix_A[x][k] * matrix_B[k][y]
    return matrix_C_element

# Define matrices A and B
matrix_A = np.ones((dim, dim))
matrix_B = np.ones((dim, dim))

# Define the total number of elements in the matrices
total_numbers = dim * dim
numbers = list(range(total_numbers))

# Execute the matrix multiplication 
result_ids = []
for i in numbers:
    data = (matrix_A, matrix_B, i)
    result_ids.append(my_function.remote(data))

# Gather results
results = ray.get(result_ids)

# Create matrix C for storing the result
matrix_C = np.zeros((dim, dim))

# Fill matrix C with values
for i in range(dim):
    for j in range(dim):
        matrix_C[i][j] = results[j * dim + i]

print(matrix_C)


[[100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 ...
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]]
